theme: minima
title: Mastermind challenge
author: David Orejuela, Emma Navarro, Santiago Peña, Nathaly Sotomayor
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here you found How to write a Mastermind game in Python.

# social links
twitter_username: nathsotomayor # DO NOT include the @ character, or else the build will fail!
github_username:  nathsotomayor # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
